spring:
  application:
    name: demo
  profiles:
    active: dev
  data:
    redis:
      host: localhost
      port: 6379

openai:
  model: gpt-4o

dialogflow:
  project-id: hybrid-chatbot

ai:
  server:
    url: http://13.125.102.69:8000